volumes:
    postgres-data:
        external: true
services:
  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=qlink
      - POSTGRES_PASSWORD=qlink
      - POSTGRES_DB=qlink
    ports:
      - 15432:5432
  fastapi:
    build:
      context: qlink-service
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./qlink-service:/app
    environment:
      SIGNING_KEY: qlink
      WAIT_HOSTS: db:5432
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
      DATABASE_URL: postgresql://qlink:qlink@db/qlink

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000
